apiVersion: v1
kind: Pod
metadata:
  name: instagram-replica
  labels:
    app: instagram-replica
spec:
  containers:
  - name: instagram-replica
    image: backend:latest
    ports:
    - containerPort: 3000
  restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: instagram-replica
spec:
  type: NodePort
  selector:
    app: instagram-replica
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: instagram-replica
spec:
  replicas: 1
  selector:
    matchLabels:
      app: instagram-replica
  template:
    metadata:
      labels:
        app: instagram-replica
    spec:
      containers:
      - name: instagram-replica
        image: backend:latest
        ports:
        - containerPort: 3000